### ISSUE TITLE
compiling peaks

### ISSUE THREAD

**Issue by skasks** [r4yan2/peaks#7]
Hi, I failed to compile all of peaks, because:

[ 94%] Building CXX object main/CMakeFiles/peaks.dir/main.cc.o
[ 96%] Linking CXX executable ../../bin/peaks-test
/usr/bin/ld: ../recon_daemon/librecon_daemon.a(Utils.cc.o): in function `RECON_Utils::create_folders(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
Utils.cc:(.text+0x197): undefined reference to `boost::filesystem::detail::create_directories(boost::filesystem::path const&, boost::system::error_code*)'
/usr/bin/ld: CMakeFiles/peaks-test.dir/main.cc.o: in function `main':
main.cc:(.text.startup+0xd): undefined reference to `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
collect2: error: ld returned 1 exit status
make[2]: *** [test/CMakeFiles/peaks-test.dir/build.make:153: ../bin/peaks-test] Error 1
make[1]: *** [CMakeFiles/Makefile2:538: test/CMakeFiles/peaks-test.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs...

 compile_libraries.sh  run through and left  boost_1_69_0.tar.bz2 behind, so I guess, this is the source being used.

There are peaks and peaks_stripped in bin, which I used for the tests. 

It took me a while to notice, that peaks_test is not required.

**Comment by r4yan2** [comment]
My fault, the tests were a work in progress (I really should merge the test branch), and ended up on master by mistake, so that error as you noticed is misleading.

**Comment by r4yan2** [comment]
I've changed a bit the build process to avoid leftover, deceiving messages or useless steps
40bcbdd5b6e03f76b4af511777bce6a3d290b810
562b626002ee8377bc79eee7c3682ecd366b36d3
48242d31809132bc1cf4f18b94760834dd1f2b3b

**Comment by skasks** [comment]
Thanks, works like charm now :+1:
