### ISSUE TITLE
Minimum requirements for peaks

### ISSUE THREAD

**Issue by skasks** [r4yan2/peaks#8]
As already pointed out, a fairly recent version of cmake is required. In Debian stretch you can pip upgrade cmake.

The supplied SQL schema gave me an an 
ERROR 1071 (42000) at line 200 in file: './database/schema.sql': Specified key was too long; max key length is 767 bytes
error, so I had to upgrade mariadb, too.
This I did upgrading my Ubuntu LTS to current "normal" channel, it is now: 10.3.17-0ubuntu0.19.04.1

**Comment by r4yan2** [comment]
Addressed in 
93679d6437033c580994afdd563358460f8b767e
cab0a80d405b2768548ffdac2e98d6bc625f2327

High requirement were never necessary: it's just my default setup (debian testing + docker). Lowered both cmake and mariadb/mysql to "standard" one hopefully without side-effects
